### ISSUE TITLE
Broken on mobile

### ISSUE THREAD

**Issue by frankdugan3** [javisperez/vuelongpress#1]
This is a really neat idea! I noticed that this does not seem to work on mobile (iOS 10.2.1 Safari), at least in the JSFiddle demo. I'm assuming this is because touch handled simulates mouseup/mousedown much differently than it behaves on desktop.

**Comment by javisperez** [comment]
Hey, thanks for the issue! honestly i completely forgot about testing on mobile, so thank you for reporting this. I'll make a few tests / fixes and make another release when done :) thanks a lot!

**Comment by javisperez** [comment]
This should be fixed now with https://github.com/javisperez/vuelongpress/releases/tag/v1.0.1

Feel free to test :)
